[package]
name = "game_assets"
version = "0.0.0"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }

[addresses]
std = "0x1"
sui = "0x2"
local = "0xF"

[dev-addresses]